[package]
name = 'cord-primitives'
version = '0.5.7'
edition = '2021'
authors = ['Dhiway <info@dhiway.com>']

[dependencies]
#serde = { version = "1.0.130", optional = true, features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["bit-vec", "derive"] }
codec = { package = "parity-scale-codec", version = "2.3.1", default-features = false, features = ["bit-vec", "derive"] }
sp-core = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.13"}
frame-system = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.13"}
sp-runtime = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.13"}
sp-std = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.13"}
sp-application-crypto = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.13"}
frame-support = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.13"}

[features]
default = ["std"]
std = [
  "codec/std",
  "scale-info/std",
  "frame-system/std",
 	"sp-application-crypto/std",
  "sp-core/std",
  "sp-runtime/std",
  "sp-std/std"
]