[package]
name = 'pallet-registry'
description = 'Manage Registries'
version = '0.8.0'
authors = ['Dhiway Networks <info@dhiway.com>']
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41" }

[dev-dependencies]
# env_logger = {version = "0.9.0"}
sp-core = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", features = ["std"]}
sp-keystore = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", features = ["std"]}
pallet-balances = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", features = ["std"]}
cord-utilities = { package = "cord-utilities", path="../../utilities", features = ["mock"] }

[dependencies]
codec = { package = "parity-scale-codec", version = "3.3.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
bitflags = {version = "1.3.2", default-features = false}
serde = { version = "1.0.136", optional = true }
log = { version = "0.4.17", default-features = false  }

# Internal dependencies
cord-primitives = { package = "cord-primitives", path="../../primitives", default-features = false }
cord-utilities = { package = "cord-utilities", path = "../../utilities", default-features = false }
pallet-schema = {  default-features = false, path = '../schema' }

# Substrate dependencies
frame-benchmarking = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false, optional = true }
frame-support = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false }
frame-system = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false }
pallet-balances = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false, optional = true }
sp-core = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false, optional = true }
sp-io = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false, optional = true }
sp-keystore = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false, optional = true }
sp-runtime = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false }
sp-std = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false }


[features]
default = [ 'std' ]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "cord-utilities/runtime-benchmarks",
]
std = [
  "codec/std",
  "frame-benchmarking/std",
  "frame-support/std",
  "frame-system/std",
  "cord-primitives/std",
  "cord-utilities/std",
  "log/std",
  "pallet-balances/std",
  "scale-info/std",
  "sp-core/std",
  "sp-io/std",
  "sp-keystore/std",
  "sp-runtime/std",
  "sp-std/std",
  "pallet-schema/std", 
]
try-runtime = [
  "frame-support/try-runtime",
  "frame-system/try-runtime",
]
