[package]
name = 'pallet-link'
version = '0.5.2'
edition = '2018'
authors = ['Dhiway <info@dhiway.com>']
description = 'Enables adding Mark Links.'

[[package.metadata.docs.rs]]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = "4.0.0"

[dependencies]
codec = {default-features = false,features = ['derive'], package = 'parity-scale-codec', version = '2.0.0' }
cord-primitives = { package = "cord-primitives", path="../../primitives", optional = true, default-features = false }
serde = { version = "1.0.123", optional = true }
pallet-entity = {  default-features = false, path = '../entity' }
pallet-mark = {  default-features = false, path = '../mark' }
pallet-schema = {  default-features = false, path = '../schema' }

# Substrate dependencies
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false }
log = {default-features = false, version = "0.4.14"}
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false, optional = true}
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false, optional = true}
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false, optional = true}
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false, optional = true}

[dev-dependencies]
cord-primitives = { package = "cord-primitives", path="../../primitives", default-features = false }
serde = { version = "1.0.123" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false }

[features]
default = [ 'std' ]
mock = [
  "cord-primitives",
  "serde",
  "sp-core",
  "sp-io",
  "sp-keystore"
]
runtime-benchmarks = [
  "frame-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
]
std = [
  "codec/std",
  "frame-support/std",
  "frame-system/std",
  "cord-primitives/std",
  "log/std",
  "sp-core/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
  "pallet-entity/std",
  "pallet-mark/std",
  "pallet-schema/std",
]