name: Multi-Arch Docker Build

on:
  push:
    branches:
      - develop
      - release-v[0-9]+.[0-9]+.[0-9]+*
  schedule:
    - cron: "00 03 * * 0" # Runs every Sunday at 3 AM UTC

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      USERNAME: dhiway
      IMAGE_NAME: ${{ github.event.repository.name }}
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Set build profile
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/release*" ]]; then
            echo "BUILD_PROFILE=production" >> $GITHUB_ENV
            echo "RELEASE_BRANCH=true" >> $GITHUB_ENV
            echo "LATEST_TAG=true" >> $GITHUB_ENV
          else
            echo "BUILD_PROFILE=release" >> $GITHUB_ENV
            echo "RELEASE_BRANCH=false" >> $GITHUB_ENV
          fi

      - name: Build and Push to Docker Hub
        run: |
          docker buildx create --use
          DOCKER_BRANCH=${{ github.ref_name }}

          docker buildx build --platform linux/amd64,linux/arm64 \
            --build-arg CARGO_PROFILE=${{ env.BUILD_PROFILE }} \
            --build-arg RELEASE_BRANCH=${{ env.RELEASE_BRANCH }} \
            --tag ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:$DOCKER_BRANCH \
            --tag ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }} \
            --file docker/Dockerfile \
            --push \
            .

          if [[ "${{ env.LATEST_TAG }}" == "true" ]]; then
            docker buildx imagetools create \
              --tag ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.RELEASE_IMAGE_NAME }}:latest \
              ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.RELEASE_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          fi

      - name: Verify Image Tags
        run: |
          echo "Docker Image Tags:"
          echo " - ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:$DOCKER_BRANCH"
          echo " - ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }}"
          if [[ "${{ env.LATEST_TAG }}" == "true" ]]; then
            echo " - ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.RELEASE_IMAGE_NAME }}:latest"
          fi
